### ISSUE TITLE
have you considered using the BatchService?

### ISSUE THREAD

**Issue by RayBB** [michal-kapala/pocketbase-import#1]
Hey there,

Thanks for the great tool.
Have you considered using the batch service for imports? 
https://github.com/pocketbase/js-sdk?tab=readme-ov-file#batchservice

It seems like it could speed things up a little?
Also, it might be nice if there was a progress indicator for the import like very 100 records or something.

Thanks!

**Comment by michal-kapala** [comment]
Bleeding edge stuff, lets try it out

**Comment by michal-kapala** [comment]
Batch APIs now supported with [v0.23.2](https://github.com/michal-kapala/pocketbase-import/releases/tag/v0.23.2), should be a massive perf boost for large files. You can tinker with the settings in the PB dashboard (*Settings > Application*), make sure to enable the thing before importing.

Batch request size is now configurable via `max_batch` option, it should never exceed `Max allowed batch requests` or all requests will fail.

Added basic logs for every batch request so you can see the progress in the console.

**Comment by michal-kapala** [comment]
Well after some testing there are limitations regarding max allowed batch requests, the number cant be as high as i expected; im applying a hotfix

**Comment by michal-kapala** [comment]
Done, that should be it for batch api support

**Comment by RayBB** [comment]
Awesome thanks @michal-kapala and this tool is just wonderful.
I used it to import some data I'm cleaning for OpenLibrary.org and it's such a huge help :)
